# Generated by Django 4.1.3 on 2022-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("date_limited", models.DateField(null=True)),
                ("asignado_a", models.CharField(max_length=20, null=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("HIGH", "HIGH"),
                            ("MEDIUM", "MEDIUM"),
                            ("LOW", "LOW"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
